# Generated by Django 3.2.9 on 2021-11-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8, null=True)),
                ('celular', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=20, null=True)),
                ('especialidad', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('area', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
    ]
